import {
  Ear, Eye, Baby, Brain, Heart, Bone, Scissors, Pill, Syringe,
  Activity, Scan, Wind, Smile, Apple, Droplets, Flame,
  Microscope, ShieldCheck, Dna, Stethoscope, HandHelping,
  CircleDot, Footprints, Flower2, Waves, Sparkles, Ribbon,
  HeartPulse, ScanEye, FlaskConical, Zap, BriefcaseMedical
} from "lucide-react";

const SPECIALTY_ICON_MAP = {
  "אודיולוגיה ושמיעה": Ear,
  "אונקולוגיה": Ribbon,
  "אופטיקה": ScanEye,
  "אוקולופלסטיקה": Eye,
  "אורולוגיה": Activity,
  "אורתופדיה": Bone,
  "אורתופדיה ילדים": Bone,
  "אלרגולוגיה ואימונולוגיה": ShieldCheck,
  "אנדוקרינולוגיה": FlaskConical,
  "אנדוקרינולוגיה ילדים": FlaskConical,
  "אף אוזן גרון": Ear,
  "אף אוזן גרון ילדים": Ear,
  "גנטיקה": Dna,
  "גניקולוגיה": Flower2,
  "גסטרואנטרולוגיה": Pill,
  "גסטרואנטרולוגיה ילדים": Pill,
  "גריאטריה": HandHelping,
  "דיאטה והרזייה": Apple,
  "המטולוגיה": Droplets,
  "טיפול במדרסים": Footprints,
  "ילדים": Baby,
  "כאב": Zap,
  "כירופרקטיקה": Bone,
  "כירורגיה אורולוגית": Scissors,
  "כירורגיה אורתופדית": Scissors,
  "כירורגיה ילדים": Scissors,
  "כירורגיה כלי דם": HeartPulse,
  "כירורגיה כללית": Scissors,
  "כירורגיה לב וחזה": Heart,
  "כירורגיה פלסטית ואסטתית": Sparkles,
  "כירורגיה ראש וצוואר": Scissors,
  "כירורגיה שד": Ribbon,
  "מרכז רפואי": BriefcaseMedical,
  "משפחה": Stethoscope,
  "נוירואופטלמולוגיה": Brain,
  "נוירוכירורגיה": Brain,
  "נוירולוגיה": Brain,
  "נוירולוגיה ילדים": Brain,
  "נפרולוגיה": Activity,
  "עור ומין": CircleDot,
  "עיניים": Eye,
  "עיניים ילדים": Eye,
  "פדיקור רפואי": Footprints,
  "פה ולסת": Smile,
  "פודיאטריה": Footprints,
  "פסיכולוגיה": Brain,
  "פסיכותרפיה": Brain,
  "פסיכיאטריה": Brain,
  "פרוקטולוגיה": Stethoscope,
  "פריון": Syringe,
  "קרדיולוגיה": Heart,
  "קרדיולוגיה ילדים": Heart,
  "ראומטולוגיה": Flame,
  "רדיולוגיה": Scan,
  "ריאות": Wind,
  "רפואה אסתטית": Sparkles,
  "רפואה משלימה": Flower2,
  "רפואה פנימית": Stethoscope,
  "רפואת צלילה": Waves,
  "שיניים": Smile,
};

export function getSpecialtyIcon(specialty) {
  return SPECIALTY_ICON_MAP[specialty] || Stethoscope;
}

export default SPECIALTY_ICON_MAP;